import type { Database, Person, Event, Encounter, Interaction, PainPoint, Promise, Edge } from "./types";

const people: Person[] = [
  {
    id: "p1",
    fullName: "Jaime López-Moreno",
    aliases: ["Jaime"],
    role: "CTO",
    company: "Flexo Retail",
    sector: "retail",
    seniority: "c-level",
    location: "Madrid",
    handles: { linkedin: "jaimelopezmoreno", email: "jaime@flexo.es", phone: "+34 611 222 333" },
    category: "cliente-potencial",
    temperature: "caliente",
    tags: ["visión-artificial", "retail", "decision-maker"],
    interests: ["computer vision", "gestión de stock"],
    affinity: 4,
    trust: 4,
    nextStep: "Enviar propuesta de POC de visión artificial para inventario",
    createdAt: "2025-10-12T09:20:00Z",
    updatedAt: "2026-04-08T11:00:00Z",
  },
  {
    id: "p2",
    fullName: "Jaime Torres Villanueva",
    aliases: ["Jaime T."],
    role: "Senior SWE",
    company: "Glovo",
    sector: "logistica",
    seniority: "senior",
    location: "Barcelona",
    handles: { linkedin: "jaimetorresv" },
    category: "talento",
    temperature: "tibio",
    tags: ["backend", "Go", "k8s"],
    interests: ["sistemas distribuidos"],
    affinity: 3,
    trust: 3,
    createdAt: "2026-02-20T10:00:00Z",
    updatedAt: "2026-03-22T14:00:00Z",
  },
  {
    id: "p3",
    fullName: "Jaime Ruiz",
    role: "Fundador",
    company: "Cronos.ai",
    sector: "saas",
    seniority: "founder",
    location: "Valencia",
    handles: { linkedin: "jaimeruizcronos", instagram: "jairuiz" },
    category: "partner",
    temperature: "caliente",
    tags: ["AI", "partner-potencial"],
    interests: ["agents", "RAG"],
    affinity: 5,
    trust: 5,
    nextStep: "Explorar joint-venture para proyecto pharma",
    createdAt: "2024-06-15T09:00:00Z",
    updatedAt: "2026-04-15T18:00:00Z",
  },
  {
    id: "p4",
    fullName: "Marta Arrieta",
    role: "Principal",
    company: "Kibo Ventures",
    sector: "otro",
    seniority: "senior",
    location: "Madrid",
    handles: { linkedin: "martaarrieta", email: "marta@kibo.vc" },
    category: "inversor",
    temperature: "tibio",
    tags: ["VC", "seed", "deep-tech"],
    interests: ["AI aplicada B2B", "vertical SaaS"],
    affinity: 4,
    trust: 4,
    nextStep: "Enviar update trimestral en mayo",
    createdAt: "2025-03-10T12:00:00Z",
    updatedAt: "2026-03-02T09:30:00Z",
  },
  {
    id: "p5",
    fullName: "Álvaro Martínez Peña",
    role: "CEO",
    company: "Logipro",
    sector: "logistica",
    seniority: "c-level",
    location: "Zaragoza",
    handles: { linkedin: "alvaromartinezp", email: "alvaro@logipro.com" },
    category: "cliente-potencial",
    temperature: "caliente",
    tags: ["forecasting", "operaciones"],
    interests: ["demand forecasting", "optimización rutas"],
    affinity: 4,
    trust: 3,
    nextStep: "Cerrar reunión con su equipo de ops",
    createdAt: "2025-11-04T08:45:00Z",
    updatedAt: "2026-04-10T12:00:00Z",
  },
  {
    id: "p6",
    fullName: "Lucía Fernández",
    role: "Data Lead",
    company: "Idealista",
    sector: "saas",
    seniority: "senior",
    location: "Madrid",
    handles: { linkedin: "luciafernandezdata" },
    category: "amigo",
    temperature: "caliente",
    tags: ["data", "MLOps"],
    interests: ["LLMs", "ML infra"],
    affinity: 5,
    trust: 5,
    createdAt: "2023-09-01T10:00:00Z",
    updatedAt: "2026-04-01T11:00:00Z",
  },
  {
    id: "p7",
    fullName: "Ricardo Solís",
    role: "VP Engineering",
    company: "Banco Sabadell",
    sector: "fintech",
    seniority: "c-level",
    location: "Barcelona",
    handles: { linkedin: "ricardosolis", email: "r.solis@bancsabadell.com" },
    category: "cliente-potencial",
    temperature: "tibio",
    tags: ["banca", "enterprise"],
    interests: ["fraud detection", "atención al cliente"],
    affinity: 3,
    trust: 3,
    nextStep: "Re-contactar Q3 cuando tenga budget",
    createdAt: "2025-05-20T14:00:00Z",
    updatedAt: "2026-01-15T10:00:00Z",
  },
  {
    id: "p8",
    fullName: "Sofía Ramírez",
    role: "Founder & CEO",
    company: "Meduza Health",
    sector: "salud",
    seniority: "founder",
    location: "Madrid",
    handles: { linkedin: "sofiaramirez", instagram: "sofi.ramz" },
    category: "partner",
    temperature: "caliente",
    tags: ["healthtech", "founders-club"],
    interests: ["clinical NLP", "data privacy"],
    affinity: 5,
    trust: 4,
    nextStep: "Co-presentar en AI Spain Conference",
    createdAt: "2025-01-18T10:00:00Z",
    updatedAt: "2026-04-12T16:00:00Z",
  },
  {
    id: "p9",
    fullName: "Guillermo de la Vega",
    role: "Managing Partner",
    company: "Seaya Ventures",
    sector: "otro",
    seniority: "c-level",
    location: "Madrid",
    handles: { linkedin: "guillermodelavega" },
    category: "inversor",
    temperature: "frio",
    tags: ["VC", "growth"],
    affinity: 2,
    trust: 3,
    createdAt: "2025-06-07T09:00:00Z",
    updatedAt: "2025-10-10T12:00:00Z",
  },
  {
    id: "p10",
    fullName: "Carmen Aguirre",
    role: "Head of Innovation",
    company: "Mapfre",
    sector: "fintech",
    seniority: "senior",
    location: "Madrid",
    handles: { linkedin: "carmenaguirre" },
    category: "cliente-potencial",
    temperature: "tibio",
    tags: ["insurance", "innovation"],
    interests: ["document AI", "claims automation"],
    affinity: 3,
    trust: 3,
    nextStep: "Pedir intro vía Marta",
    createdAt: "2025-10-02T15:00:00Z",
    updatedAt: "2026-03-28T10:00:00Z",
  },
  {
    id: "p11",
    fullName: "Diego Peña Ortiz",
    role: "CPO",
    company: "TravelPerk",
    sector: "saas",
    seniority: "c-level",
    location: "Barcelona",
    handles: { linkedin: "diegopenaortiz" },
    category: "cliente-potencial",
    temperature: "tibio",
    tags: ["product", "B2B-travel"],
    interests: ["copilots", "agents"],
    affinity: 3,
    trust: 3,
    createdAt: "2026-02-28T09:00:00Z",
    updatedAt: "2026-03-30T14:00:00Z",
  },
  {
    id: "p12",
    fullName: "Patricia Molina",
    role: "CEO",
    company: "Noustic",
    sector: "edtech",
    seniority: "founder",
    location: "Valencia",
    handles: { linkedin: "patriciamolina" },
    category: "partner",
    temperature: "tibio",
    tags: ["edtech", "founder"],
    interests: ["adaptive learning", "LLMs educación"],
    affinity: 4,
    trust: 4,
    createdAt: "2025-09-15T10:00:00Z",
    updatedAt: "2026-02-18T11:00:00Z",
  },
  {
    id: "p13",
    fullName: "Iker Ballester",
    role: "Senior ML Engineer",
    company: "Freepik",
    sector: "media",
    seniority: "senior",
    location: "Málaga",
    handles: { linkedin: "ikerballester", twitter: "ikerbal" },
    category: "talento",
    temperature: "caliente",
    tags: ["computer vision", "diffusion", "contratar-Q3"],
    interests: ["image generation", "CV"],
    affinity: 4,
    trust: 4,
    nextStep: "Cerrar oferta antes de cambio de ronda",
    createdAt: "2025-11-22T09:00:00Z",
    updatedAt: "2026-04-14T16:00:00Z",
  },
  {
    id: "p14",
    fullName: "Noelia Cruz",
    role: "COO",
    company: "Clicars",
    sector: "ecommerce",
    seniority: "c-level",
    location: "Madrid",
    handles: { linkedin: "noeliacruz" },
    category: "cliente-potencial",
    temperature: "frio",
    tags: ["ops", "automoción"],
    interests: ["pricing dinámico"],
    affinity: 2,
    trust: 2,
    createdAt: "2025-07-10T12:00:00Z",
    updatedAt: "2025-12-01T15:00:00Z",
  },
  {
    id: "p15",
    fullName: "Roberto Castaño",
    role: "Founder",
    company: "Castaño Industries",
    sector: "industria",
    seniority: "founder",
    location: "Bilbao",
    handles: { linkedin: "robertocastanoindustries", email: "roberto@castano.es" },
    category: "cliente-potencial",
    temperature: "caliente",
    tags: ["industria-4.0", "family-business"],
    interests: ["mantenimiento predictivo", "OCR facturas"],
    affinity: 4,
    trust: 4,
    nextStep: "Visita a planta en mayo",
    createdAt: "2025-12-10T09:00:00Z",
    updatedAt: "2026-04-11T10:00:00Z",
  },
  {
    id: "p16",
    fullName: "Elena Sainz",
    role: "Head of Data",
    company: "Cabify",
    sector: "logistica",
    seniority: "senior",
    location: "Madrid",
    handles: { linkedin: "elenasainz" },
    category: "amigo",
    temperature: "tibio",
    tags: ["data-platform"],
    interests: ["streaming", "real-time"],
    affinity: 4,
    trust: 4,
    createdAt: "2024-04-20T10:00:00Z",
    updatedAt: "2026-02-05T12:00:00Z",
  },
  {
    id: "p17",
    fullName: "Manuel Escudero",
    role: "Angel Investor",
    company: "Independiente",
    sector: "otro",
    seniority: "c-level",
    location: "Madrid",
    handles: { linkedin: "manuelescuderoangel" },
    category: "inversor",
    temperature: "caliente",
    tags: ["angel", "exitado"],
    interests: ["AI", "B2B", "enterprise"],
    affinity: 5,
    trust: 5,
    nextStep: "Invitarle a advisory board",
    createdAt: "2024-10-08T10:00:00Z",
    updatedAt: "2026-04-17T19:00:00Z",
  },
  {
    id: "p18",
    fullName: "Claudia Vázquez",
    role: "CEO",
    company: "Lingvist",
    sector: "edtech",
    seniority: "founder",
    location: "Madrid",
    handles: { linkedin: "claudiavazquez" },
    category: "partner",
    temperature: "tibio",
    tags: ["founder", "edtech"],
    affinity: 3,
    trust: 3,
    createdAt: "2025-08-22T09:00:00Z",
    updatedAt: "2026-03-04T14:00:00Z",
  },
  {
    id: "p19",
    fullName: "Hugo Benítez",
    role: "CIO",
    company: "Grupo Cortefiel",
    sector: "retail",
    seniority: "c-level",
    location: "Madrid",
    handles: { linkedin: "hugobenitez" },
    category: "cliente-potencial",
    temperature: "tibio",
    tags: ["enterprise", "fashion"],
    interests: ["merchandising", "search"],
    affinity: 3,
    trust: 3,
    createdAt: "2025-09-30T10:00:00Z",
    updatedAt: "2026-02-28T11:00:00Z",
  },
  {
    id: "p20",
    fullName: "Natalia Ordóñez",
    role: "Freelance Designer",
    company: "Independiente",
    sector: "media",
    seniority: "senior",
    location: "Sevilla",
    handles: { linkedin: "nataliaordonez", instagram: "natordesign" },
    category: "talento",
    temperature: "tibio",
    tags: ["UX", "branding"],
    affinity: 3,
    trust: 3,
    createdAt: "2025-06-12T09:00:00Z",
    updatedAt: "2026-01-25T14:00:00Z",
  },
  {
    id: "p21",
    fullName: "Andrés Vidal",
    role: "CEO",
    company: "AgroSense",
    sector: "industria",
    seniority: "founder",
    location: "Murcia",
    handles: { linkedin: "andresvidal" },
    category: "cliente-potencial",
    temperature: "tibio",
    tags: ["agrifood", "IoT"],
    interests: ["precision agriculture"],
    affinity: 3,
    trust: 3,
    createdAt: "2025-10-29T10:00:00Z",
    updatedAt: "2026-03-10T10:00:00Z",
  },
  {
    id: "p22",
    fullName: "Beatriz Mendoza",
    role: "Country Manager",
    company: "Notion",
    sector: "saas",
    seniority: "c-level",
    location: "Madrid",
    handles: { linkedin: "beatrizmendoza" },
    category: "partner",
    temperature: "tibio",
    tags: ["productividad", "partner"],
    affinity: 3,
    trust: 3,
    createdAt: "2025-11-11T15:00:00Z",
    updatedAt: "2026-03-14T11:00:00Z",
  },
  {
    id: "p23",
    fullName: "Felipe Arnau",
    role: "Head of Growth",
    company: "Factorial HR",
    sector: "saas",
    seniority: "senior",
    location: "Barcelona",
    handles: { linkedin: "felipearnau" },
    category: "amigo",
    temperature: "tibio",
    tags: ["growth", "B2B"],
    affinity: 4,
    trust: 4,
    createdAt: "2024-11-01T10:00:00Z",
    updatedAt: "2026-02-22T12:00:00Z",
  },
  {
    id: "p24",
    fullName: "Isabel Arroyo",
    role: "Director of AI",
    company: "Telefónica",
    sector: "media",
    seniority: "c-level",
    location: "Madrid",
    handles: { linkedin: "isabelarroyo" },
    category: "cliente-potencial",
    temperature: "caliente",
    tags: ["enterprise", "telco", "decision-maker"],
    interests: ["LLMs enterprise", "governance"],
    affinity: 4,
    trust: 4,
    nextStep: "Mandar deck vertical telco",
    createdAt: "2025-12-15T10:00:00Z",
    updatedAt: "2026-04-13T09:00:00Z",
  },
  {
    id: "p25",
    fullName: "Víctor Pardo",
    role: "CTO",
    company: "Civitatis",
    sector: "ecommerce",
    seniority: "c-level",
    location: "Madrid",
    handles: { linkedin: "victorpardo" },
    category: "cliente-potencial",
    temperature: "frio",
    tags: ["travel", "search"],
    affinity: 2,
    trust: 2,
    createdAt: "2025-04-10T10:00:00Z",
    updatedAt: "2025-11-20T15:00:00Z",
  },
  {
    id: "p26",
    fullName: "Cristina Herrera",
    role: "VP Operations",
    company: "Holaluz",
    sector: "energia",
    seniority: "c-level",
    location: "Barcelona",
    handles: { linkedin: "cristinaherrera" },
    category: "cliente-potencial",
    temperature: "tibio",
    tags: ["energia", "customer-ops"],
    interests: ["churn prediction", "call center AI"],
    affinity: 3,
    trust: 3,
    createdAt: "2025-09-05T10:00:00Z",
    updatedAt: "2026-03-18T12:00:00Z",
  },
  {
    id: "p27",
    fullName: "Pablo Ferrer",
    role: "Lead ML",
    company: "BBVA",
    sector: "fintech",
    seniority: "senior",
    location: "Madrid",
    handles: { linkedin: "pabloferrer" },
    category: "amigo",
    temperature: "caliente",
    tags: ["ml", "banca"],
    affinity: 5,
    trust: 5,
    createdAt: "2023-05-15T10:00:00Z",
    updatedAt: "2026-04-02T17:00:00Z",
  },
  {
    id: "p28",
    fullName: "Laura Esteban",
    role: "Partner",
    company: "JME Ventures",
    sector: "otro",
    seniority: "senior",
    location: "Madrid",
    handles: { linkedin: "lauraesteban" },
    category: "inversor",
    temperature: "tibio",
    tags: ["VC", "seed"],
    affinity: 3,
    trust: 3,
    createdAt: "2025-02-18T10:00:00Z",
    updatedAt: "2026-01-30T11:00:00Z",
  },
  {
    id: "p29",
    fullName: "Ignacio Montoya",
    role: "Founder",
    company: "LegalGPT",
    sector: "legaltech",
    seniority: "founder",
    location: "Madrid",
    handles: { linkedin: "nachomontoya" },
    category: "partner",
    temperature: "tibio",
    tags: ["legaltech", "founder"],
    interests: ["RAG jurídico"],
    affinity: 3,
    trust: 3,
    createdAt: "2025-11-28T10:00:00Z",
    updatedAt: "2026-03-06T14:00:00Z",
  },
  {
    id: "p30",
    fullName: "Elvira Sánchez",
    role: "Founder",
    company: "Bamboo Education",
    sector: "edtech",
    seniority: "founder",
    location: "Bogotá",
    handles: { linkedin: "elvirasanchez", instagram: "elvi.sanchez" },
    category: "partner",
    temperature: "tibio",
    tags: ["latam", "edtech"],
    affinity: 3,
    trust: 3,
    createdAt: "2025-10-14T10:00:00Z",
    updatedAt: "2026-02-14T10:00:00Z",
  },
  {
    id: "p31",
    fullName: "Samuel Ortíz",
    role: "CEO",
    company: "Bewe",
    sector: "saas",
    seniority: "founder",
    location: "Madrid",
    handles: { linkedin: "samuelortiz" },
    category: "partner",
    temperature: "tibio",
    tags: ["saas", "vertical"],
    affinity: 3,
    trust: 3,
    createdAt: "2025-07-01T10:00:00Z",
    updatedAt: "2026-02-10T10:00:00Z",
  },
  {
    id: "p32",
    fullName: "Teresa Bouza",
    role: "Head of Digital",
    company: "Inditex",
    sector: "retail",
    seniority: "c-level",
    location: "A Coruña",
    handles: { linkedin: "teresabouza" },
    category: "cliente-potencial",
    temperature: "caliente",
    tags: ["retail", "enterprise", "estratégico"],
    interests: ["recommender", "visual search"],
    affinity: 4,
    trust: 3,
    nextStep: "Preparar POC de visual search",
    createdAt: "2026-01-20T10:00:00Z",
    updatedAt: "2026-04-15T11:00:00Z",
  },
  {
    id: "p33",
    fullName: "Javier Colomer",
    role: "Product Lead",
    company: "Amenitiz",
    sector: "saas",
    seniority: "senior",
    location: "Barcelona",
    handles: { linkedin: "javiercolomer" },
    category: "amigo",
    temperature: "tibio",
    tags: ["product", "hospitality"],
    affinity: 3,
    trust: 4,
    createdAt: "2024-08-10T10:00:00Z",
    updatedAt: "2026-02-02T10:00:00Z",
  },
  {
    id: "p34",
    fullName: "Raquel Díaz",
    role: "CFO",
    company: "Wallbox",
    sector: "energia",
    seniority: "c-level",
    location: "Barcelona",
    handles: { linkedin: "raqueldiaz" },
    category: "cliente-potencial",
    temperature: "frio",
    tags: ["cleantech", "public-company"],
    affinity: 2,
    trust: 2,
    createdAt: "2025-05-05T10:00:00Z",
    updatedAt: "2025-11-12T15:00:00Z",
  },
  {
    id: "p35",
    fullName: "Óscar Mateu",
    role: "Serial Entrepreneur",
    company: "Independiente",
    sector: "otro",
    seniority: "founder",
    location: "Valencia",
    handles: { linkedin: "oscarmateu" },
    category: "inversor",
    temperature: "tibio",
    tags: ["angel", "mentor"],
    affinity: 4,
    trust: 4,
    createdAt: "2024-12-20T10:00:00Z",
    updatedAt: "2026-03-20T11:00:00Z",
  },
  {
    id: "p36",
    fullName: "Nerea Goikoetxea",
    role: "Engineering Manager",
    company: "Fever",
    sector: "media",
    seniority: "senior",
    location: "Madrid",
    handles: { linkedin: "nereagoikoetxea" },
    category: "talento",
    temperature: "tibio",
    tags: ["ingeniería", "management"],
    affinity: 3,
    trust: 3,
    createdAt: "2025-10-18T10:00:00Z",
    updatedAt: "2026-02-27T10:00:00Z",
  },
  {
    id: "p37",
    fullName: "Tomás Iriarte",
    role: "VC Analyst",
    company: "Samaipata",
    sector: "otro",
    seniority: "junior",
    location: "Madrid",
    handles: { linkedin: "tomasiriarte" },
    category: "inversor",
    temperature: "tibio",
    tags: ["analyst", "scout"],
    affinity: 3,
    trust: 3,
    createdAt: "2025-11-07T10:00:00Z",
    updatedAt: "2026-03-28T12:00:00Z",
  },
  {
    id: "p38",
    fullName: "Paula Navarro",
    role: "Founder",
    company: "Klosera Clinics",
    sector: "salud",
    seniority: "founder",
    location: "Valencia",
    handles: { linkedin: "paulanavarro" },
    category: "cliente-potencial",
    temperature: "tibio",
    tags: ["healthtech", "clínicas"],
    interests: ["agendas automáticas", "chatbot pacientes"],
    affinity: 3,
    trust: 3,
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-03-01T10:00:00Z",
  },
  {
    id: "p39",
    fullName: "Gonzalo Uribe",
    role: "Founder",
    company: "Urby Mobility",
    sector: "logistica",
    seniority: "founder",
    location: "Lisboa",
    handles: { linkedin: "gonzalouribe" },
    category: "partner",
    temperature: "frio",
    tags: ["mobility", "latam"],
    affinity: 2,
    trust: 2,
    createdAt: "2025-06-22T10:00:00Z",
    updatedAt: "2025-12-15T10:00:00Z",
  },
  {
    id: "p40",
    fullName: "Miriam Caballero",
    role: "Head of People",
    company: "Travelgenio",
    sector: "ecommerce",
    seniority: "senior",
    location: "Madrid",
    handles: { linkedin: "miriamcaballero" },
    category: "amigo",
    temperature: "tibio",
    tags: ["people-ops"],
    affinity: 3,
    trust: 4,
    createdAt: "2024-03-14T10:00:00Z",
    updatedAt: "2026-01-18T10:00:00Z",
  },
];

const events: Event[] = [
  { id: "e1", name: "South Summit 2025", location: "Madrid, La Nave", date: "2025-06-04", endDate: "2025-06-06", notes: "Stand compartido con Cronos.ai" },
  { id: "e2", name: "4YFN 2026", location: "Barcelona, Fira Gran Via", date: "2026-02-24", endDate: "2026-02-27" },
  { id: "e3", name: "Enlightened Madrid", location: "Madrid, The Shed", date: "2025-10-15" },
  { id: "e4", name: "Web Summit 2025", location: "Lisboa", date: "2025-11-10", endDate: "2025-11-13" },
  { id: "e5", name: "AI Spain Conference", location: "Madrid, IFEMA", date: "2026-03-18", endDate: "2026-03-19" },
  { id: "e6", name: "Startup Olé", location: "Salamanca", date: "2025-09-17", endDate: "2025-09-19" },
  { id: "e7", name: "Smart Agrifood Summit", location: "Málaga", date: "2025-10-29", endDate: "2025-10-30" },
  { id: "e8", name: "Fundraising Dinner JME", location: "Madrid, privado", date: "2026-01-28", notes: "Invitación vía Laura" },
  { id: "e9", name: "Founders Coffee (mensual)", location: "Madrid, Federal", date: "2026-04-04" },
  { id: "e10", name: "DES Madrid 2026", location: "Madrid, IFEMA", date: "2026-05-14", endDate: "2026-05-16" },
];

const encounters: Encounter[] = [
  // Jaime López (p1) — cliente caliente, varios encuentros
  { id: "en1", personId: "p1", eventId: "e1", date: "2025-06-05", location: "South Summit", context: "Primer contacto en el networking del día 2. Me lo presentó Lucía." },
  { id: "en2", personId: "p1", date: "2025-07-22", location: "Café Federal, Madrid", context: "Primer café 1:1. Hablamos de su problema de gestión de stock." },
  { id: "en3", personId: "p1", date: "2025-11-12", location: "Oficina Flexo, Madrid", context: "Reunión con su equipo de ops." },
  { id: "en4", personId: "p1", eventId: "e5", date: "2026-03-18", location: "AI Spain Conference", context: "Nos cruzamos en su ponencia. Pidió hablar pronto." },
  { id: "en5", personId: "p1", date: "2026-04-08", location: "Zoom", context: "Call para pre-propuesta POC." },

  // Jaime Torres (p2)
  { id: "en6", personId: "p2", eventId: "e2", date: "2026-02-25", location: "4YFN", context: "Charla en zona de speakers, hablamos de Go y k8s." },
  { id: "en7", personId: "p2", date: "2026-03-22", location: "Barcelona, remoto", context: "Call exploratoria, perfil interesante pero aún no timing." },

  // Jaime Ruiz (p3)
  { id: "en8", personId: "p3", date: "2024-06-15", location: "Madrid, fundadores meetup", context: "Nos conocimos en un meetup de founders de IA." },
  { id: "en9", personId: "p3", eventId: "e1", date: "2025-06-04", location: "South Summit", context: "Stand compartido los 3 días." },
  { id: "en10", personId: "p3", date: "2025-12-19", location: "Cena fin de año Valencia", context: "Cena de amigos, hablamos de joint venture pharma." },
  { id: "en11", personId: "p3", eventId: "e9", date: "2026-04-04", location: "Founders Coffee", context: "Retomamos JV pharma." },
  { id: "en12", personId: "p3", date: "2026-04-15", location: "Zoom", context: "Primera propuesta formal de estructura." },

  // Marta Arrieta (p4)
  { id: "en13", personId: "p4", date: "2025-03-10", location: "Kibo oficinas", context: "Intro fría, primera toma de contacto con Kibo." },
  { id: "en14", personId: "p4", eventId: "e4", date: "2025-11-12", location: "Web Summit Lisboa", context: "Reencuentro en sesión de VCs. Prometió intros." },
  { id: "en15", personId: "p4", eventId: "e8", date: "2026-01-28", location: "JME Dinner", context: "Cena íntima de inversores. Mencionó interés en seed AI B2B." },
  { id: "en16", personId: "p4", date: "2026-03-02", location: "Café Kibo", context: "Update de roadmap." },

  // Álvaro Martínez (p5)
  { id: "en17", personId: "p5", eventId: "e3", date: "2025-10-15", location: "Enlightened", context: "Primer contacto. Habló mucho de forecasting." },
  { id: "en18", personId: "p5", date: "2025-12-03", location: "Zaragoza, Logipro", context: "Visita a sus oficinas." },
  { id: "en19", personId: "p5", date: "2026-02-19", location: "Zoom", context: "Workshop con su equipo de datos." },
  { id: "en20", personId: "p5", date: "2026-04-10", location: "Madrid, Hotel Wellington", context: "Le pillé de paso, negociando términos de POC." },

  // Lucía Fernández (p6)
  { id: "en21", personId: "p6", date: "2023-09-01", location: "Tech Hub Madrid", context: "Compañera de antiguo rol." },
  { id: "en22", personId: "p6", eventId: "e1", date: "2025-06-05", location: "South Summit", context: "Nos cruzamos, me presentó a Jaime López." },
  { id: "en23", personId: "p6", date: "2026-01-10", location: "Cena Navidades atrasadas", context: "Cena con gente de Idealista." },
  { id: "en24", personId: "p6", date: "2026-04-01", location: "Zoom", context: "Consejo sobre arquitectura MLOps." },

  // Ricardo Solís (p7)
  { id: "en25", personId: "p7", date: "2025-05-20", location: "Barcelona, Sabadell HQ", context: "Intro vía partner de consultora." },
  { id: "en26", personId: "p7", eventId: "e4", date: "2025-11-11", location: "Web Summit", context: "Coincidimos en panel fintech." },
  { id: "en27", personId: "p7", date: "2026-01-15", location: "Zoom", context: "Sin budget hasta Q3, acordamos re-contactar." },

  // Sofía Ramírez (p8)
  { id: "en28", personId: "p8", date: "2025-01-18", location: "Meetup healthtech Madrid", context: "Nos conocimos." },
  { id: "en29", personId: "p8", eventId: "e1", date: "2025-06-06", location: "South Summit", context: "Presentamos juntos un track de salud." },
  { id: "en30", personId: "p8", date: "2026-02-11", location: "Oficina Meduza", context: "Preparar co-ponencia." },
  { id: "en31", personId: "p8", eventId: "e5", date: "2026-03-19", location: "AI Spain Conference", context: "Co-ponencia. Muy bien recibida." },
  { id: "en32", personId: "p8", date: "2026-04-12", location: "Brunch El Retiro", context: "Estrategia post-ponencia, siguientes pasos." },

  // Guillermo (p9)
  { id: "en33", personId: "p9", date: "2025-06-07", location: "Seaya oficinas", context: "Intro fría, no hubo seguimiento." },
  { id: "en34", personId: "p9", eventId: "e4", date: "2025-11-13", location: "Web Summit", context: "Saludo breve en stand." },

  // Carmen (p10)
  { id: "en35", personId: "p10", eventId: "e3", date: "2025-10-15", location: "Enlightened", context: "Nos presentó Manuel Escudero." },
  { id: "en36", personId: "p10", date: "2026-03-28", location: "Zoom", context: "Exploratoria corta, pedía intro formal." },

  // Diego Peña (p11)
  { id: "en37", personId: "p11", eventId: "e2", date: "2026-02-26", location: "4YFN", context: "Primera conversación." },
  { id: "en38", personId: "p11", date: "2026-03-30", location: "Zoom", context: "Deep dive en su roadmap de copilots." },

  // Patricia (p12)
  { id: "en39", personId: "p12", date: "2025-09-15", location: "Evento edtech Valencia", context: "Nos conocimos." },
  { id: "en40", personId: "p12", date: "2026-02-18", location: "Zoom", context: "Hablamos de posible colab." },

  // Iker Ballester (p13)
  { id: "en41", personId: "p13", date: "2025-11-22", location: "Málaga, Freepik offices", context: "Le conocí por intro de Lucía." },
  { id: "en42", personId: "p13", date: "2026-02-06", location: "Zoom", context: "Segunda entrevista." },
  { id: "en43", personId: "p13", date: "2026-04-14", location: "Madrid, comida", context: "Vino a Madrid, le hice oferta verbal." },

  // Noelia (p14)
  { id: "en44", personId: "p14", date: "2025-07-10", location: "Clicars HQ", context: "Reunión exploratoria." },

  // Roberto Castaño (p15)
  { id: "en45", personId: "p15", eventId: "e7", date: "2025-10-30", location: "Smart Agrifood Summit", context: "Nos conocimos, curioso que estuviera ahí." },
  { id: "en46", personId: "p15", date: "2026-01-25", location: "Llamada", context: "Me describió necesidades de mantenimiento predictivo." },
  { id: "en47", personId: "p15", date: "2026-04-11", location: "Zoom", context: "Pre-agendar visita a planta." },

  // Elena Sainz (p16)
  { id: "en48", personId: "p16", date: "2024-04-20", location: "Antigua compañera", context: "Ex compañera de trabajo." },
  { id: "en49", personId: "p16", date: "2026-02-05", location: "Café", context: "Catch up personal." },

  // Manuel Escudero (p17) — angel, muchos encuentros
  { id: "en50", personId: "p17", date: "2024-10-08", location: "Cena de founders", context: "Intro por partner común." },
  { id: "en51", personId: "p17", eventId: "e3", date: "2025-10-15", location: "Enlightened", context: "Reencuentro. Me presentó a Carmen." },
  { id: "en52", personId: "p17", eventId: "e8", date: "2026-01-28", location: "JME Dinner", context: "Habló muy bien del equipo." },
  { id: "en53", personId: "p17", eventId: "e9", date: "2026-04-04", location: "Founders Coffee", context: "Discusión sobre advisory role." },
  { id: "en54", personId: "p17", date: "2026-04-17", location: "Cena Madrid", context: "Cena íntima. Aceptó entrar al advisory." },

  // Claudia (p18)
  { id: "en55", personId: "p18", date: "2025-08-22", location: "Evento edtech", context: "Intro por Patricia." },
  { id: "en56", personId: "p18", date: "2026-03-04", location: "Zoom", context: "Update, timing no encaja." },

  // Hugo Benítez (p19)
  { id: "en57", personId: "p19", date: "2025-09-30", location: "Cortefiel HQ", context: "Reunión exploratoria." },
  { id: "en58", personId: "p19", date: "2026-02-28", location: "Zoom", context: "Interesa pero bloqueado por IT." },

  // Natalia (p20)
  { id: "en59", personId: "p20", eventId: "e6", date: "2025-09-18", location: "Startup Olé", context: "Hicimos talk juntos." },
  { id: "en60", personId: "p20", date: "2026-01-25", location: "Sevilla, visita", context: "Encargo de diseño de deck." },

  // Andrés Vidal (p21)
  { id: "en61", personId: "p21", eventId: "e7", date: "2025-10-29", location: "Smart Agrifood Summit", context: "Nos conocimos ahí." },
  { id: "en62", personId: "p21", date: "2026-03-10", location: "Zoom", context: "Exploratoria." },

  // Beatriz (p22)
  { id: "en63", personId: "p22", date: "2025-11-11", location: "Notion España launch", context: "Nos presentamos." },
  { id: "en64", personId: "p22", date: "2026-03-14", location: "Café", context: "Hablamos de potencial partnership." },

  // Felipe Arnau (p23)
  { id: "en65", personId: "p23", date: "2024-11-01", location: "Meetup Barcelona", context: "Nos conocimos." },
  { id: "en66", personId: "p23", eventId: "e2", date: "2026-02-26", location: "4YFN", context: "Cena informal con varios founders." },

  // Isabel Arroyo (p24) — cliente muy estratégico
  { id: "en67", personId: "p24", date: "2025-12-15", location: "Telefónica HQ", context: "Intro vía Pablo Ferrer." },
  { id: "en68", personId: "p24", eventId: "e5", date: "2026-03-19", location: "AI Spain Conference", context: "Coincidencia, conversación larga." },
  { id: "en69", personId: "p24", date: "2026-04-13", location: "Zoom", context: "Pide deck vertical telco urgente." },

  // Víctor Pardo (p25)
  { id: "en70", personId: "p25", date: "2025-04-10", location: "Civitatis HQ", context: "Reunión única, no hubo seguimiento." },

  // Cristina Herrera (p26)
  { id: "en71", personId: "p26", date: "2025-09-05", location: "Barcelona, Holaluz", context: "Exploratoria." },
  { id: "en72", personId: "p26", date: "2026-03-18", location: "Zoom", context: "Interesada en churn prediction." },

  // Pablo Ferrer (p27) — amigo
  { id: "en73", personId: "p27", date: "2023-05-15", location: "Madrid, antigua empresa", context: "Ex compañero." },
  { id: "en74", personId: "p27", date: "2026-01-12", location: "Café", context: "Me presentó a Isabel." },
  { id: "en75", personId: "p27", date: "2026-04-02", location: "Cena Madrid", context: "Cena mensual habitual." },

  // Laura Esteban (p28)
  { id: "en76", personId: "p28", date: "2025-02-18", location: "JME oficinas", context: "Intro." },
  { id: "en77", personId: "p28", eventId: "e8", date: "2026-01-28", location: "JME Dinner", context: "Anfitriona." },

  // Ignacio Montoya (p29)
  { id: "en78", personId: "p29", date: "2025-11-28", location: "Meetup legaltech", context: "Conocimos." },
  { id: "en79", personId: "p29", date: "2026-03-06", location: "Café", context: "Exploratoria colab." },

  // Elvira (p30)
  { id: "en80", personId: "p30", date: "2025-10-14", location: "Visita Bogotá", context: "Me presentó un partner en LatAm." },
  { id: "en81", personId: "p30", date: "2026-02-14", location: "Zoom", context: "Seguimiento." },

  // Samuel (p31)
  { id: "en82", personId: "p31", date: "2025-07-01", location: "Madrid, Bewe offices", context: "Primera reunión." },
  { id: "en83", personId: "p31", date: "2026-02-10", location: "Zoom", context: "Segunda conversación." },

  // Teresa Bouza (p32) — cliente caliente
  { id: "en84", personId: "p32", date: "2026-01-20", location: "Coruña, Inditex HQ", context: "Intro por partner de ex-cliente." },
  { id: "en85", personId: "p32", date: "2026-02-28", location: "Zoom", context: "Prep técnica." },
  { id: "en86", personId: "p32", eventId: "e5", date: "2026-03-18", location: "AI Spain Conference", context: "Coincidimos rápidamente." },
  { id: "en87", personId: "p32", date: "2026-04-15", location: "Coruña, reunión técnica", context: "POC aprobado en principio." },

  // Javier Colomer (p33)
  { id: "en88", personId: "p33", date: "2024-08-10", location: "Barcelona, meetup", context: "Nos conocimos." },
  { id: "en89", personId: "p33", date: "2026-02-02", location: "Zoom", context: "Catch up." },

  // Raquel Díaz (p34)
  { id: "en90", personId: "p34", date: "2025-05-05", location: "Barcelona, Wallbox", context: "Reunión única." },

  // Óscar Mateu (p35)
  { id: "en91", personId: "p35", date: "2024-12-20", location: "Valencia, cena founders", context: "Nos conocimos." },
  { id: "en92", personId: "p35", eventId: "e9", date: "2026-04-04", location: "Founders Coffee Madrid", context: "Reencuentro." },
  { id: "en93", personId: "p35", date: "2026-03-20", location: "Zoom", context: "Charla sobre su nueva empresa." },

  // Nerea (p36)
  { id: "en94", personId: "p36", date: "2025-10-18", location: "Madrid, Fever offices", context: "Intro vía Elena." },
  { id: "en95", personId: "p36", date: "2026-02-27", location: "Café", context: "Exploratoria." },

  // Tomás (p37)
  { id: "en96", personId: "p37", date: "2025-11-07", location: "Samaipata offices", context: "Analyst, primera charla." },
  { id: "en97", personId: "p37", date: "2026-03-28", location: "Zoom", context: "Update trimestral." },

  // Paula Navarro (p38)
  { id: "en98", personId: "p38", date: "2026-01-10", location: "Valencia, Klosera", context: "Conocí por intro Patricia." },
  { id: "en99", personId: "p38", date: "2026-03-01", location: "Zoom", context: "Segunda." },

  // Gonzalo (p39)
  { id: "en100", personId: "p39", date: "2025-06-22", location: "Lisboa, Web Summit precursor event", context: "Brevísimo." },

  // Miriam (p40)
  { id: "en101", personId: "p40", date: "2024-03-14", location: "Cena amigos Madrid", context: "Conocida desde hace años." },
  { id: "en102", personId: "p40", date: "2026-01-18", location: "Café", context: "Catch up personal." },
];

const painPoints: PainPoint[] = [
  { id: "pp1", personId: "p1", description: "Gestión de stock manual en 42 tiendas. Desperdicio >8%", createdAt: "2025-07-22", sourceInteractionId: "i2" },
  { id: "pp2", personId: "p1", description: "Problemas con reconteos: errores de cuadratura constantes.", createdAt: "2025-11-12" },
  { id: "pp3", personId: "p5", description: "Previsión de demanda con Excel, error ~22% en SKUs estacionales.", createdAt: "2025-10-15" },
  { id: "pp4", personId: "p5", description: "Optimización de rutas se hace a ojo por el jefe de flota.", createdAt: "2025-12-03" },
  { id: "pp5", personId: "p7", description: "Fraude transaccional con modelos viejos, tasa de falsos positivos alta.", createdAt: "2025-05-20" },
  { id: "pp6", personId: "p10", description: "90% de siniestros tramitados a mano, time-to-close alto.", createdAt: "2025-10-15" },
  { id: "pp7", personId: "p15", description: "Paradas inesperadas de CNC cuestan 80k€ al mes.", createdAt: "2026-01-25" },
  { id: "pp8", personId: "p15", description: "Proceso de facturación manual con proveedores, media 6 min/factura.", createdAt: "2026-04-11" },
  { id: "pp9", personId: "p24", description: "Despliegue de LLMs bloqueado por compliance interno. Necesita governance clara.", createdAt: "2026-04-13" },
  { id: "pp10", personId: "p26", description: "Tasa de churn del 14% y sin modelo predictivo funcional.", createdAt: "2026-03-18" },
  { id: "pp11", personId: "p32", description: "Búsqueda visual actual no aprovecha imagen de catálogo propio.", createdAt: "2026-02-28" },
  { id: "pp12", personId: "p38", description: "Agendas de clínicas no-shows 18%, sin recordatorios inteligentes.", createdAt: "2026-03-01" },
  { id: "pp13", personId: "p21", description: "Datos de sensores IoT silenciados en CSVs, sin pipeline.", createdAt: "2026-03-10" },
  { id: "pp14", personId: "p11", description: "Quieren lanzar agente de soporte pero no saben por dónde empezar.", createdAt: "2026-03-30" },
  { id: "pp15", personId: "p29", description: "Rule-based actual de LegalGPT escala mal, quieren pasar a RAG.", createdAt: "2026-03-06" },
];

const promises: Promise[] = [
  { id: "pr1", personId: "p1", description: "Enviar propuesta de POC inventario", direction: "yo-a-el", dueDate: "2026-04-22", done: false, createdAt: "2026-04-08" },
  { id: "pr2", personId: "p4", description: "Mandar update trimestral", direction: "yo-a-el", dueDate: "2026-05-01", done: false, createdAt: "2026-03-02" },
  { id: "pr3", personId: "p4", description: "Intro a Carmen Aguirre (Mapfre)", direction: "el-a-mi", dueDate: "2026-04-25", done: false, createdAt: "2026-03-02" },
  { id: "pr4", personId: "p5", description: "Firmar NDA POC", direction: "yo-a-el", done: true, createdAt: "2026-02-19" },
  { id: "pr5", personId: "p13", description: "Mandar oferta formal por email", direction: "yo-a-el", dueDate: "2026-04-21", done: false, createdAt: "2026-04-14" },
  { id: "pr6", personId: "p15", description: "Agendar visita planta", direction: "yo-a-el", dueDate: "2026-05-10", done: false, createdAt: "2026-04-11" },
  { id: "pr7", personId: "p17", description: "Enviarle estructura del advisory", direction: "yo-a-el", dueDate: "2026-04-24", done: false, createdAt: "2026-04-17" },
  { id: "pr8", personId: "p24", description: "Preparar deck vertical telco", direction: "yo-a-el", dueDate: "2026-04-20", done: false, createdAt: "2026-04-13" },
  { id: "pr9", personId: "p32", description: "Enviar borrador de plan POC visual search", direction: "yo-a-el", dueDate: "2026-04-23", done: false, createdAt: "2026-04-15" },
  { id: "pr10", personId: "p10", description: "Presentarme formalmente vía email", direction: "el-a-mi", dueDate: "2026-04-19", done: false, createdAt: "2026-03-28" },
  { id: "pr11", personId: "p8", description: "Compartir grabación de ponencia", direction: "yo-a-el", done: true, createdAt: "2026-03-22" },
  { id: "pr12", personId: "p3", description: "Primer borrador términos JV pharma", direction: "yo-a-el", dueDate: "2026-04-30", done: false, createdAt: "2026-04-15" },
];

const interactions: Interaction[] = encounters.map((en, idx) => ({
  id: `i${idx + 1}`,
  personId: en.personId,
  kind: "encuentro",
  date: en.date,
  summary: en.context ?? "Encuentro",
  encounterId: en.id,
}));

interactions.push(
  { id: "i201", personId: "p1", kind: "email", date: "2025-07-30", summary: "Le mandé deck corporativo tras primer café" },
  { id: "i202", personId: "p1", kind: "llamada", date: "2026-02-05", summary: "Llamada de 25 min para saber estado tras Navidades" },
  { id: "i203", personId: "p3", kind: "mensaje", date: "2026-03-12", summary: "WhatsApp aleatorio: me propuso tema pharma" },
  { id: "i204", personId: "p4", kind: "email", date: "2025-12-20", summary: "Felicitación Navidad + reminder" },
  { id: "i205", personId: "p17", kind: "mensaje", date: "2026-04-10", summary: "Le propuse entrar al advisory" },
  { id: "i206", personId: "p24", kind: "email", date: "2026-04-14", summary: "Follow-up con deck en borrador" },
  { id: "i207", personId: "p27", kind: "mensaje", date: "2026-04-16", summary: "Cotilleo interno BBVA, info útil para Isabel" },
  { id: "i208", personId: "p32", kind: "email", date: "2026-04-16", summary: "Resumen ejecutivo post reunión" },
);

const edges: Edge[] = [
  { id: "eg1", fromPersonId: "p6", toPersonId: "p1", kind: "presentado-por", note: "Lucía me presentó a Jaime en South Summit" },
  { id: "eg2", fromPersonId: "p17", toPersonId: "p10", kind: "presentado-por", note: "Manuel me presentó a Carmen" },
  { id: "eg3", fromPersonId: "p27", toPersonId: "p24", kind: "presentado-por", note: "Pablo me presentó a Isabel" },
  { id: "eg4", fromPersonId: "p12", toPersonId: "p18", kind: "presentado-por" },
  { id: "eg5", fromPersonId: "p12", toPersonId: "p38", kind: "presentado-por" },
  { id: "eg6", fromPersonId: "p6", toPersonId: "p13", kind: "presentado-por", note: "Lucía me habló de Iker en Freepik" },
  { id: "eg7", fromPersonId: "p4", toPersonId: "p10", kind: "conoce", note: "Marta y Carmen colaboran en red de innovation heads" },
  { id: "eg8", fromPersonId: "p3", toPersonId: "p6", kind: "conoce" },
  { id: "eg9", fromPersonId: "p17", toPersonId: "p35", kind: "conoce", note: "Manuel y Óscar coinciden en varias rondas angel" },
  { id: "eg10", fromPersonId: "p8", toPersonId: "p38", kind: "conoce", note: "Ambas healthtech" },
  { id: "eg11", fromPersonId: "p28", toPersonId: "p37", kind: "trabaja-con", note: "JME y Samaipata co-invierten" },
  { id: "eg12", fromPersonId: "p4", toPersonId: "p28", kind: "conoce" },
  { id: "eg13", fromPersonId: "p27", toPersonId: "p6", kind: "conoce" },
  { id: "eg14", fromPersonId: "p16", toPersonId: "p36", kind: "presentado-por", note: "Elena me presentó a Nerea" },
  { id: "eg15", fromPersonId: "p3", toPersonId: "p8", kind: "trabaja-con", note: "Colab de Cronos con Meduza" },
  { id: "eg16", fromPersonId: "p17", toPersonId: "p4", kind: "inversor-de", note: "Manuel ha invertido con Kibo" },
  { id: "eg17", fromPersonId: "p11", toPersonId: "p33", kind: "conoce", note: "Ambos en ecosistema Barcelona" },
  { id: "eg18", fromPersonId: "p23", toPersonId: "p33", kind: "conoce" },
  { id: "eg19", fromPersonId: "p32", toPersonId: "p24", kind: "conoce", note: "Inditex y Telefónica en mismos foros" },
  { id: "eg20", fromPersonId: "p40", toPersonId: "p16", kind: "conoce" },
];

export const mockDatabase: Database = {
  people,
  events,
  encounters,
  interactions,
  painPoints,
  promises,
  edges,
};
